export const symptoms = [
  "Nausea",
  "Vomiting",
  "Dizziness",
  "Vertigo",
  "Light sensitivity",
  "Sound sensitivity",
  "Smell sensitivity",
  "Visual aura",
  "Sensory aura",
  "Fatigue",
  "Brain fog",
  "Neck pain",
  "Neck stiffness",
  "Eye pain",
  "Watery/bloodshot eyes",
  "Sweating",
  "Weakness",
  "Other",
];
export const factors = [
  "Poor sleep",
  "Oversleeping",
  "Dehydration",
  "Skipped meal",
  "Stress",
  "Emotional stress",
  "Prolonged screen time",
  "Gaming",
  "Headset use",
  "Neck tension",
  "Poor posture",
  "Prolonged sitting",
  "Exercise",
  "Lack of exercise",
  "Caffeine",
  "Caffeine withdrawal",
  "Weather",
  "Heat",
  "Bright light",
  "Illness",
  "Medication timing",
  "Missed medication",
  "Unknown",
];
export const locations = [
  "Behind eyes",
  "Forehead",
  "Temple",
  "Back of head",
  "Neck",
  "Other",
];
export const characters = [
  "Throbbing",
  "Pressure",
  "Sharp",
  "Pulsating",
  "Stabbing",
  "Tightness",
  "Other",
];
export const activities = [
  "Gym/exercise",
  "Normal activity",
  "Reduced activity",
  "Mostly resting",
  "Working",
  "Gaming/screen-heavy day",
];
export const disruptions = [
  "Missed work",
  "Skipped gym",
  "Cancelled plans",
  "Poor sleep",
  "Reduced household activity",
];
export const impacts = [
  "No impact",
  "Mild",
  "Had to reduce activities",
  "Stopped normal activities",
  "Mostly confined to bed/rest",
  "Unable to function normally",
];
export const sideEffects = [
  "Morning grogginess",
  "Daytime sleepiness",
  "Dizziness",
  "Appetite increase",
  "Dry mouth",
  "Constipation",
  "Nausea",
  "Mood change",
  "Other",
];
export const medicationNames = [
  "Pizotifen / Sandomigran",
  "Rizatriptan / Maxalt",
  "Paracetamol",
  "Ibuprofen",
];
